name: chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.3
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf


flutter_native_splash:
  color: "#2B475E"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: "assets/images/splash.png"
    color: "#2B475E"