name: chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.8
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.6
  firebase_messaging: ^14.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf


flutter_native_splash:
  color: "#2B475E"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: "assets/images/splash.png"
    color: "#2B475E"